//! Huge-tier CBOR benchmarks, in a separate binary from `huge_file.rs` to avoid
//! OOM on memory-constrained machines.
//!
//! CBOR decode loads only the CBOR fixture (~400 MB) and decodes it.
//! CBOR encode loads the CBOR fixture, decodes it once into an `OmtsFile`,
//! drops the raw bytes, then benchmarks encoding.
//!
//! Fixtures are pre-generated by `just gen-huge`.
//! Run via `just bench-huge-cbor` or `cargo bench -p omtsf-bench --bench huge_cbor`.
#![allow(clippy::expect_used)]

use criterion::{BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use omtsf_bench::huge_cbor_fixture_path;
use omtsf_core::OmtsFile;
use omtsf_core::cbor::{decode_cbor, encode_cbor};

fn bench_huge_cbor_decode(c: &mut Criterion) {
    let path = huge_cbor_fixture_path();
    eprintln!("Loading huge CBOR fixture from {}...", path.display());
    let cbor =
        std::fs::read(&path).expect("Failed to read huge CBOR fixture. Run `just gen-huge` first.");
    let cbor_size = cbor.len() as u64;
    eprintln!(
        "CBOR fixture: {:.1} MB",
        cbor_size as f64 / (1024.0 * 1024.0)
    );

    let mut group = c.benchmark_group("huge/cbor_decode");
    group.sample_size(10);
    group.measurement_time(std::time::Duration::from_secs(30));
    group.throughput(Throughput::Bytes(cbor_size));

    group.bench_function(BenchmarkId::from_parameter("Huge"), |b| {
        b.iter(|| {
            let _ = decode_cbor(&cbor).expect("decode cbor");
        });
    });
    group.finish();
}

fn bench_huge_cbor_encode(c: &mut Criterion) {
    let path = huge_cbor_fixture_path();
    eprintln!("Loading huge CBOR fixture for encode benchmark...");
    let cbor =
        std::fs::read(&path).expect("Failed to read huge CBOR fixture. Run `just gen-huge` first.");
    let cbor_size = cbor.len() as u64;

    eprintln!("Decoding CBOR to get OmtsFile...");
    let file: OmtsFile = decode_cbor(&cbor).expect("decode cbor");
    drop(cbor);
    eprintln!(
        "Ready: {} nodes, {} edges",
        file.nodes.len(),
        file.edges.len()
    );

    let mut group = c.benchmark_group("huge/cbor_encode");
    group.sample_size(10);
    group.measurement_time(std::time::Duration::from_secs(20));
    group.throughput(Throughput::Bytes(cbor_size));

    group.bench_function(BenchmarkId::from_parameter("Huge"), |b| {
        b.iter(|| {
            let _ = encode_cbor(&file).expect("encode cbor");
        });
    });
    group.finish();
}

criterion_group!(benches, bench_huge_cbor_decode, bench_huge_cbor_encode,);
criterion_main!(benches);
